server:
  port: 19830
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: nvr-playback
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

fdfs:
  serverUrl: http://10.102.1.173:8888/
  fileDownUrl: /opt/business
  groupName: group1
  fileExtension: jpg,png,html,htm,zip,gltf,glb,svg,xls,xlsx
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 10.102.1.173:22122
  pool:
    jmx-enabled: false
    ## 连接池最大数量
    max-total: 200
    ## 每个tracker地址的最大连接数
    max-total-per-key: 50
    ## 连接耗尽时等待获取连接的最大毫秒数
    max-wait-millis: 5000